In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel('Work Context.xlsx')
print(df)
type(df)

       O*NET-SOC Code                              Title   Element ID  \
0          11-1011.00                   Chief Executives  4.C.1.a.2.c
1          11-1011.00                   Chief Executives  4.C.1.a.2.c
2          11-1011.00                   Chief Executives  4.C.1.a.2.c
3          11-1011.00                   Chief Executives  4.C.1.a.2.c
4          11-1011.00                   Chief Executives  4.C.1.a.2.c
...               ...                                ...          ...
326879     53-7121.00  Tank Car, Truck, and Ship Loaders    4.C.3.d.4
326880     53-7121.00  Tank Car, Truck, and Ship Loaders    4.C.3.d.8
326881     53-7121.00  Tank Car, Truck, and Ship Loaders    4.C.3.d.8
326882     53-7121.00  Tank Car, Truck, and Ship Loaders    4.C.3.d.8
326883     53-7121.00  Tank Car, Truck, and Ship Loaders    4.C.3.d.8

                         Element Name Scale ID                Scale Name  \
0                     Public Speaking       CX                   Context
1                     Public Speaking      CXP  Context (Categories 1-5)
2                     Public Speaking      CXP  Context (Categories 1-5)
3                     Public Speaking      CXP  Context (Categories 1-5)
4                     Public Speaking      CXP  Context (Categories 1-5)
...                               ...      ...                       ...
326879                 Work Schedules      CTP  Context (Categories 1-3)
326880  Duration of Typical Work Week       CT                   Context
326881  Duration of Typical Work Week      CTP  Context (Categories 1-3)
326882  Duration of Typical Work Week      CTP  Context (Categories 1-3)
326883  Duration of Typical Work Week      CTP  Context (Categories 1-3)

        Category  Data Value     N  Standard Error  Lower CI Bound  \
0            NaN        3.39  25.0            0.22            2.93
1            1.0        6.02  25.0            5.14            0.97
2            2.0       12.40  25.0            7.33            3.39
3            3.0       23.36  25.0           10.36            8.45
4            4.0       52.55  25.0           12.13           28.87
...          ...         ...   ...             ...             ...
326879       3.0        0.89  32.0            0.98            0.09
326880       NaN        2.82  32.0            0.10            2.62
326881       1.0        0.00  32.0            0.00             NaN
326882       2.0       17.56  32.0            9.83            5.06
326883       3.0       82.44  32.0            9.83           54.01

        Upper CI Bound Recommend Suppress  Not Relevant     Date Domain Source
0                 3.86                  N           NaN  07/2014     Incumbent
1                29.49                  N           NaN  07/2014     Incumbent
2                36.32                  N           NaN  07/2014     Incumbent
3                50.16                  N           NaN  07/2014     Incumbent
4                75.14                  N           NaN  07/2014     Incumbent
...                ...                ...           ...      ...           ...
326879            7.87                  N           NaN  08/2019     Incumbent
326880            3.00                  N           NaN  08/2019     Incumbent
326881             NaN                  N           NaN  08/2019     Incumbent
326882           45.99                  N           NaN  08/2019     Incumbent
326883           94.94                  N           NaN  08/2019     Incumbent

[326884 rows x 16 columns]

pandas.core.frame.DataFrame

In [55]:
dftxt = pd.read_csv('Work_Context.txt', sep='\t')
print(dftxt)
type(dftxt)

       O*NET-SOC Code   Element ID                   Element Name Scale ID  \
0          11-1011.00  4.C.1.a.2.c                Public Speaking       CX
1          11-1011.00  4.C.1.a.2.c                Public Speaking      CXP
2          11-1011.00  4.C.1.a.2.c                Public Speaking      CXP
3          11-1011.00  4.C.1.a.2.c                Public Speaking      CXP
4          11-1011.00  4.C.1.a.2.c                Public Speaking      CXP
...               ...          ...                            ...      ...
264433     53-7121.00    4.C.3.d.4                 Work Schedules      CTP
264434     53-7121.00    4.C.3.d.8  Duration of Typical Work Week       CT
264435     53-7121.00    4.C.3.d.8  Duration of Typical Work Week      CTP
264436     53-7121.00    4.C.3.d.8  Duration of Typical Work Week      CTP
264437     53-7121.00    4.C.3.d.8  Duration of Typical Work Week      CTP

        Category  Data Value     N  Standard Error  Lower CI Bound  \
0            NaN        3.47  27.0            0.55            2.33
1            1.0       14.55  27.0           13.42            1.82
2            2.0        2.39  27.0            1.82            0.49
3            3.0       31.56  27.0           15.59            9.47
4            4.0       24.71  27.0           15.87            5.38
...          ...         ...   ...             ...             ...
264433       3.0        1.28  16.0            1.43            0.12
264434       NaN        2.76  16.0            0.15            2.44
264435       1.0        0.00  16.0            0.00             NaN
264436       2.0       23.54  16.0           15.42            4.73
264437       3.0       76.46  16.0           15.42           34.35

        Upper CI Bound Recommend Suppress  Not Relevant     Date Domain Source
0                 4.61                  N           NaN  06/2006     Incumbent
1                61.04                  N           NaN  06/2006     Incumbent
2                10.86                  N           NaN  06/2006     Incumbent
3                67.03                  N           NaN  06/2006     Incumbent
4                65.47                  N           NaN  06/2006     Incumbent
...                ...                ...           ...      ...           ...
264433           12.69                  N           NaN  12/2006     Incumbent
264434            3.00                  N           NaN  12/2006     Incumbent
264435             NaN                  N           NaN  12/2006     Incumbent
264436           65.65                  N           NaN  12/2006     Incumbent
264437           95.27                  N           NaN  12/2006     Incumbent

[264438 rows x 14 columns]

pandas.core.frame.DataFrame

In [3]:
df = pd.read_excel('Work Contextmid.xlsx')
print(df)
type(df)

       O*NET-SOC Code                              Title   Element ID  \
0          11-1011.00                   Chief Executives  4.C.1.a.2.c
1          11-1011.00                   Chief Executives  4.C.1.a.2.c
2          11-1011.00                   Chief Executives  4.C.1.a.2.c
3          11-1011.00                   Chief Executives  4.C.1.a.2.c
4          11-1011.00                   Chief Executives  4.C.1.a.2.c
...               ...                                ...          ...
321585     53-7121.00  Tank Car, Truck, and Ship Loaders    4.C.3.d.4
321586     53-7121.00  Tank Car, Truck, and Ship Loaders    4.C.3.d.8
321587     53-7121.00  Tank Car, Truck, and Ship Loaders    4.C.3.d.8
321588     53-7121.00  Tank Car, Truck, and Ship Loaders    4.C.3.d.8
321589     53-7121.00  Tank Car, Truck, and Ship Loaders    4.C.3.d.8

                         Element Name Scale ID                Scale Name  \
0                     Public Speaking       CX                   Context
1                     Public Speaking      CXP  Context (Categories 1-5)
2                     Public Speaking      CXP  Context (Categories 1-5)
3                     Public Speaking      CXP  Context (Categories 1-5)
4                     Public Speaking      CXP  Context (Categories 1-5)
...                               ...      ...                       ...
321585                 Work Schedules      CTP  Context (Categories 1-3)
321586  Duration of Typical Work Week       CT                   Context
321587  Duration of Typical Work Week      CTP  Context (Categories 1-3)
321588  Duration of Typical Work Week      CTP  Context (Categories 1-3)
321589  Duration of Typical Work Week      CTP  Context (Categories 1-3)

        Category  Data Value     N  Standard Error  Lower CI Bound  \
0            NaN        3.39  25.0            0.22            2.93
1            1.0        6.02  25.0            5.14            0.97
2            2.0       12.40  25.0            7.33            3.39
3            3.0       23.36  25.0           10.36            8.45
4            4.0       52.55  25.0           12.13           28.87
...          ...         ...   ...             ...             ...
321585       3.0        1.28  16.0            1.43            0.12
321586       NaN        2.76  16.0            0.15            2.44
321587       1.0        0.00  16.0            0.00             NaN
321588       2.0       23.54  16.0           15.42            4.73
321589       3.0       76.46  16.0           15.42           34.35

        Upper CI Bound Recommend Suppress  Not Relevant     Date Domain Source
0                 3.86                  N           NaN  07/2014     Incumbent
1                29.49                  N           NaN  07/2014     Incumbent
2                36.32                  N           NaN  07/2014     Incumbent
3                50.16                  N           NaN  07/2014     Incumbent
4                75.14                  N           NaN  07/2014     Incumbent
...                ...                ...           ...      ...           ...
321585           12.69                  N           NaN  12/2006     Incumbent
321586            3.00                  N           NaN  12/2006     Incumbent
321587             NaN                  N           NaN  12/2006     Incumbent
321588           65.65                  N           NaN  12/2006     Incumbent
321589           95.27                  N           NaN  12/2006     Incumbent

[321590 rows x 16 columns]

pandas.core.frame.DataFrame

In [4]:
true = pd.DataFrame(df, columns = ["O*NET-SOC Code", 'Title', 'Element Name', 'Category', 'Data Value', 'Date'])
true

,O*NET-SOC Code,Title,Element Name,Category,Data Value,Date
0,11-1011.00,Chief Executives,Public Speaking,NaN,3.39,07/2014
1,11-1011.00,Chief Executives,Public Speaking,1.0,6.02,07/2014
2,11-1011.00,Chief Executives,Public Speaking,2.0,12.40,07/2014
3,11-1011.00,Chief Executives,Public Speaking,3.0,23.36,07/2014
4,11-1011.00,Chief Executives,Public Speaking,4.0,52.55,07/2014
...,...,...,...,...,...,...
326879,53-7121.00,"Tank Car, Truck, and Ship Loaders",Work Schedules,3.0,0.89,08/2019
326880,53-7121.00,"Tank Car, Truck, and Ship Loaders",Duration of Typical Work Week,NaN,2.82,08/2019
326881,53-7121.00,"Tank Car, Truck, and Ship Loaders",Duration of Typical Work Week,1.0,0.00,08/2019
326882,53-7121.00,"Tank Car, Truck, and Ship Loaders",Duration of Typical Work Week,2.0,17.56,08/2019
326883,53-7121.00,"Tank Car, Truck, and Ship Loaders",Duration of Typical Work Week,3.0,82.44,08/2019

In [110]:
dftxt= pd.DataFrame(df, columns = ['O*NET-SOC Code', 'Element Name', 'Category', 'Data Value', 'Date'])
dftxt

     O*NET-SOC Code  Element Name  Category  Data Value  Date
0               NaN           NaN       NaN         NaN   NaN
1               NaN           NaN       NaN         NaN   NaN
2               NaN           NaN       NaN         NaN   NaN
3               NaN           NaN       NaN         NaN   NaN
4               NaN           NaN       NaN         NaN   NaN
..              ...           ...       ...         ...   ...
949             NaN           NaN       NaN         NaN   NaN
950             NaN           NaN       NaN         NaN   NaN
951             NaN           NaN       NaN         NaN   NaN
952             NaN           NaN       NaN         NaN   NaN
953             NaN           NaN       NaN         NaN   NaN

[954 rows x 5 columns]

In [5]:
true[true.Category != 'NaN']
#true['Category'] = true['Category'].fillna(0)
# converted NaN to 0

C:\Users\ajj4p\Documents\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  res_values = method(rvalues)

,Title,Element Name,Category,Data Value,Date
0,Chief Executives,Public Speaking,NaN,3.39,07/2014
1,Chief Executives,Public Speaking,1.0,6.02,07/2014
2,Chief Executives,Public Speaking,2.0,12.40,07/2014
3,Chief Executives,Public Speaking,3.0,23.36,07/2014
4,Chief Executives,Public Speaking,4.0,52.55,07/2014
...,...,...,...,...,...
321585,"Tank Car, Truck, and Ship Loaders",Work Schedules,3.0,1.28,12/2006
321586,"Tank Car, Truck, and Ship Loaders",Duration of Typical Work Week,NaN,2.76,12/2006
321587,"Tank Car, Truck, and Ship Loaders",Duration of Typical Work Week,1.0,0.00,12/2006
321588,"Tank Car, Truck, and Ship Loaders",Duration of Typical Work Week,2.0,23.54,12/2006
321589,"Tank Car, Truck, and Ship Loaders",Duration of Typical Work Week,3.0,76.46,12/2006

In [109]:
dftxt[dftxt.Category != 'NaN']

C:\Users\ajj4p\Documents\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  res_values = method(rvalues)

     O*NET-SOC Code  Element Name  Category  Data Value  Date
0               NaN           NaN       NaN         NaN   NaN
1               NaN           NaN       NaN         NaN   NaN
2               NaN           NaN       NaN         NaN   NaN
3               NaN           NaN       NaN         NaN   NaN
4               NaN           NaN       NaN         NaN   NaN
..              ...           ...       ...         ...   ...
949             NaN           NaN       NaN         NaN   NaN
950             NaN           NaN       NaN         NaN   NaN
951             NaN           NaN       NaN         NaN   NaN
952             NaN           NaN       NaN         NaN   NaN
953             NaN           NaN       NaN         NaN   NaN

[954 rows x 5 columns]

In [6]:
Unititle = true.Title.unique()
Unititle

array(['Chief Executives', 'Chief Sustainability Officers',
       'General and Operations Managers',
       'Advertising and Promotions Managers', 'Marketing Managers',
       'Sales Managers', 'Public Relations and Fundraising Managers',
       'Administrative Services Managers',
       'Computer and Information Systems Managers',
       'Treasurers and Controllers',
       'Financial Managers, Branch or Department',
       'Industrial Production Managers',
       'Quality Control Systems Managers',
       'Geothermal Production Managers', 'Biomass Power Plant Managers',
       'Purchasing Managers', 'Transportation Managers',
       'Storage and Distribution Managers', 'Logistics Managers',
       'Compensation and Benefits Managers', 'Human Resources Managers',
       'Training and Development Managers',
       'Nursery and Greenhouse Managers', 'Farm and Ranch Managers',
       'Aquacultural Managers', 'Construction Managers',
       'Education Administrators, Preschool and Childcare Center/Program',
       'Education Administrators, Elementary and Secondary School',
       'Education Administrators, Postsecondary',
       'Distance Learning Coordinators',
       'Fitness and Wellness Coordinators',
       'Architectural and Engineering Managers',
       'Biofuels/Biodiesel Technology and Product Development Managers',
       'Food Service Managers', 'Funeral Service Managers',
       'Gaming Managers', 'Lodging Managers',
       'Medical and Health Services Managers',
       'Natural Sciences Managers', 'Clinical Research Coordinators',
       'Water Resource Specialists',
       'Postmasters and Mail Superintendents',
       'Property, Real Estate, and Community Association Managers',
       'Social and Community Service Managers',
       'Emergency Management Directors', 'Regulatory Affairs Managers',
       'Compliance Managers', 'Investment Fund Managers',
       'Supply Chain Managers', 'Security Managers',
       'Loss Prevention Managers',
       'Brownfield Redevelopment Specialists and Site Managers',
       'Agents and Business Managers of Artists, Performers, and Athletes',
       'Buyers and Purchasing Agents, Farm Products',
       'Wholesale and Retail Buyers, Except Farm Products',
       'Purchasing Agents, Except Wholesale, Retail, and Farm Products',
       'Claims Examiners, Property and Casualty Insurance',
       'Insurance Adjusters, Examiners, and Investigators',
       'Insurance Appraisers, Auto Damage',
       'Environmental Compliance Inspectors',
       'Licensing Examiners and Inspectors',
       'Equal Opportunity Representatives and Officers',
       'Government Property Inspectors and Investigators', 'Coroners',
       'Regulatory Affairs Specialists', 'Cost Estimators',
       'Human Resources Specialists', 'Farm Labor Contractors',
       'Labor Relations Specialists', 'Logisticians',
       'Logistics Engineers', 'Logistics Analysts', 'Management Analysts',
       'Meeting, Convention, and Event Planners', 'Fundraisers',
       'Compensation, Benefits, and Job Analysis Specialists',
       'Training and Development Specialists',
       'Market Research Analysts and Marketing Specialists',
       'Energy Auditors', 'Security Management Specialists',
       'Customs Brokers', 'Business Continuity Planners',
       'Sustainability Specialists', 'Online Merchants', 'Accountants',
       'Auditors', 'Assessors', 'Appraisers, Real Estate',
       'Budget Analysts', 'Credit Analysts', 'Financial Analysts',
       'Personal Financial Advisors', 'Insurance Underwriters',
       'Financial Examiners', 'Credit Counselors', 'Loan Counselors',
       'Loan Officers',
       'Tax Examiners and Collectors, and Revenue Agents',
       'Tax Preparers', 'Risk Management Specialists',
       'Fraud Examiners, Investigators and Analysts',
       'Computer and Information Research Scientists',
       'Computer Systems Analysts', 'Informatics Nurse Specialists',
       'Information Security Analysts', 'Computer Programmers',
       'Software Developers, Applications',
       'Software Developers, Systems Software', 'Web Developers',
       'Database Administrators',
       'Network and Computer Systems Administrators',
       'Computer Network Architects',
       'Telecommunications Engineering Specialists',
       'Computer User Support Specialists',
       'Computer Network Support Specialists',
       'Software Quality Assurance Engineers and Testers',
       'Computer Systems Engineers/Architects', 'Web Administrators',
       'Geospatial Information Scientists and Technologists',
       'Geographic Information Systems Technicians',
       'Database Architects', 'Business Intelligence Analysts',
       'Information Technology Project Managers',
       'Search Marketing Strategists', 'Video Game Designers',
       'Document Management Specialists', 'Actuaries', 'Mathematicians',
       'Operations Research Analysts', 'Statisticians',
       'Biostatisticians', 'Clinical Data Managers',
       'Mathematical Technicians',
       'Architects, Except Landscape and Naval', 'Landscape Architects',
       'Cartographers and Photogrammetrists', 'Surveyors',
       'Geodetic Surveyors', 'Aerospace Engineers',
       'Agricultural Engineers', 'Biomedical Engineers',
       'Chemical Engineers', 'Civil Engineers',
       'Transportation Engineers', 'Computer Hardware Engineers',
       'Electrical Engineers', 'Electronics Engineers, Except Computer',
       'Radio Frequency Identification Device Specialists',
       'Environmental Engineers', 'Water/Wastewater Engineers',
       'Industrial Safety and Health Engineers',
       'Fire-Prevention and Protection Engineers',
       'Product Safety Engineers', 'Industrial Engineers',
       'Human Factors Engineers and Ergonomists', 'Marine Engineers',
       'Marine Architects', 'Materials Engineers', 'Mechanical Engineers',
       'Fuel Cell Engineers', 'Automotive Engineers',
       'Mining and Geological Engineers, Including Mining Safety Engineers',
       'Nuclear Engineers', 'Petroleum Engineers',
       'Biochemical Engineers', 'Validation Engineers',
       'Energy Engineers', 'Manufacturing Engineers',
       'Mechatronics Engineers', 'Photonics Engineers',
       'Robotics Engineers', 'Nanosystems Engineers',
       'Wind Energy Engineers', 'Solar Energy Systems Engineers',
       'Architectural Drafters', 'Civil Drafters', 'Electronic Drafters',
       'Electrical Drafters', 'Mechanical Drafters',
       'Aerospace Engineering and Operations Technicians',
       'Civil Engineering Technicians',
       'Electronics Engineering Technicians',
       'Electrical Engineering Technicians',
       'Electro-Mechanical Technicians', 'Robotics Technicians',
       'Environmental Engineering Technicians',
       'Industrial Engineering Technicians',
       'Mechanical Engineering Technicians',
       'Non-Destructive Testing Specialists',
       'Electrical Engineering Technologists',
       'Electromechanical Engineering Technologists',
       'Electronics Engineering Technologists',
       'Industrial Engineering Technologists',
       'Manufacturing Engineering Technologists',
       'Mechanical Engineering Technologists', 'Photonics Technicians',
       'Manufacturing Production Technicians', 'Surveying Technicians',
       'Mapping Technicians', 'Animal Scientists',
       'Food Scientists and Technologists', 'Soil and Plant Scientists',
       'Biologists', 'Biochemists and Biophysicists', 'Microbiologists',
       'Zoologists and Wildlife Biologists', 'Bioinformatics Scientists',
       'Molecular and Cellular Biologists', 'Geneticists',
       'Soil and Water Conservationists', 'Range Managers',
       'Park Naturalists', 'Foresters', 'Epidemiologists',
       'Medical Scientists, Except Epidemiologists', 'Astronomers',
       'Physicists', 'Atmospheric and Space Scientists', 'Chemists',
       'Materials Scientists',
       'Environmental Scientists and Specialists, Including Health',
       'Climate Change Analysts', 'Environmental Restoration Planners',
       'Industrial Ecologists',
       'Geoscientists, Except Hydrologists and Geographers',
       'Hydrologists', 'Remote Sensing Scientists and Technologists',
       'Economists', 'Environmental Economists', 'Survey Researchers',
       'School Psychologists', 'Clinical Psychologists',
       'Counseling Psychologists',
       'Industrial-Organizational Psychologists',
       'Neuropsychologists and Clinical Neuropsychologists',
       'Sociologists', 'Urban and Regional Planners', 'Anthropologists',
       'Archeologists', 'Geographers', 'Historians',
       'Political Scientists', 'Transportation Planners',
       'Agricultural Technicians', 'Food Science Technicians',
       'Biological Technicians', 'Chemical Technicians',
       'Geophysical Data Technicians',
       'Geological Sample Test Technicians',
       'Nuclear Equipment Operation Technicians',
       'Nuclear Monitoring Technicians',
       'Social Science Research Assistants',
       'City and Regional Planning Aides',
       'Environmental Science and Protection Technicians, Including Health',
       'Forensic Science Technicians',
       'Forest and Conservation Technicians', 'Quality Control Analysts',
       'Precision Agriculture Technicians', 'Remote Sensing Technicians',
       'Substance Abuse and Behavioral Disorder Counselors',
       'Educational, Guidance, School, and Vocational Counselors',
       'Marriage and Family Therapists', 'Mental Health Counselors',
       'Rehabilitation Counselors',
       'Child, Family, and School Social Workers',
       'Healthcare Social Workers',
       'Mental Health and Substance Abuse Social Workers',
       'Health Educators',
       'Probation Officers and Correctional Treatment Specialists',
       'Social and Human Service Assistants', 'Community Health Workers',
       'Clergy', 'Directors, Religious Activities and Education',
       'Lawyers', 'Judicial Law Clerks',
       'Administrative Law Judges, Adjudicators, and Hearing Officers',
       'Arbitrators, Mediators, and Conciliators',
       'Judges, Magistrate Judges, and Magistrates',
       'Paralegals and Legal Assistants', 'Court Reporters',
       'Title Examiners, Abstractors, and Searchers',
       'Business Teachers, Postsecondary',
       'Computer Science Teachers, Postsecondary',
       'Mathematical Science Teachers, Postsecondary',
       'Architecture Teachers, Postsecondary',
       'Engineering Teachers, Postsecondary',
       'Agricultural Sciences Teachers, Postsecondary',
       'Biological Science Teachers, Postsecondary',
       'Forestry and Conservation Science Teachers, Postsecondary',
       'Atmospheric, Earth, Marine, and Space Sciences Teachers, Postsecondary',
       'Chemistry Teachers, Postsecondary',
       'Environmental Science Teachers, Postsecondary',
       'Physics Teachers, Postsecondary',
       'Anthropology and Archeology Teachers, Postsecondary',
       'Area, Ethnic, and Cultural Studies Teachers, Postsecondary',
       'Economics Teachers, Postsecondary',
       'Geography Teachers, Postsecondary',
       'Political Science Teachers, Postsecondary',
       'Psychology Teachers, Postsecondary',
       'Sociology Teachers, Postsecondary',
       'Health Specialties Teachers, Postsecondary',
       'Nursing Instructors and Teachers, Postsecondary',
       'Education Teachers, Postsecondary',
       'Library Science Teachers, Postsecondary',
       'Criminal Justice and Law Enforcement Teachers, Postsecondary',
       'Law Teachers, Postsecondary',
       'Social Work Teachers, Postsecondary',
       'Art, Drama, and Music Teachers, Postsecondary',
       'Communications Teachers, Postsecondary',
       'English Language and Literature Teachers, Postsecondary',
       'Foreign Language and Literature Teachers, Postsecondary',
       'History Teachers, Postsecondary',
       'Philosophy and Religion Teachers, Postsecondary',
       'Graduate Teaching Assistants',
       'Home Economics Teachers, Postsecondary',
       'Recreation and Fitness Studies Teachers, Postsecondary',
       'Vocational Education Teachers, Postsecondary',
       'Preschool Teachers, Except Special Education',
       'Kindergarten Teachers, Except Special Education',
       'Elementary School Teachers, Except Special Education',
       'Middle School Teachers, Except Special and Career/Technical Education',
       'Career/Technical Education Teachers, Middle School',
       'Secondary School Teachers, Except Special and Career/Technical Education',
       'Career/Technical Education Teachers, Secondary School',
       'Special Education Teachers, Kindergarten and Elementary School',
       'Special Education Teachers, Middle School',
       'Special Education Teachers, Secondary School',
       'Adapted Physical Education Specialists',
       'Adult Basic and Secondary Education and Literacy Teachers and Instructors',
       'Self-Enrichment Education Teachers', 'Tutors', 'Archivists',
       'Curators', 'Museum Technicians and Conservators', 'Librarians',
       'Library Technicians',
       'Audio-Visual and Multimedia Collections Specialists',
       'Farm and Home Management Advisors', 'Instructional Coordinators',
       'Instructional Designers and Technologists', 'Teacher Assistants',
       'Art Directors', 'Craft Artists',
       'Fine Artists, Including Painters, Sculptors, and Illustrators',
       'Multimedia Artists and Animators',
       'Commercial and Industrial Designers', 'Fashion Designers',
       'Floral Designers', 'Graphic Designers', 'Interior Designers',
       'Merchandise Displayers and Window Trimmers',
       'Set and Exhibit Designers', 'Actors', 'Producers',
       'Directors- Stage, Motion Pictures, Television, and Radio',
       'Program Directors', 'Talent Directors',
       'Technical Directors/Managers', 'Athletes and Sports Competitors',
       'Coaches and Scouts',
       'Umpires, Referees, and Other Sports Officials', 'Dancers',
       'Choreographers', 'Music Directors',
       'Music Composers and Arrangers', 'Singers',
       'Musicians, Instrumental', 'Radio and Television Announcers',
       'Public Address System and Other Announcers',
       'Broadcast News Analysts', 'Reporters and Correspondents',
       'Public Relations Specialists', 'Editors', 'Technical Writers',
       'Copy Writers', 'Poets, Lyricists and Creative Writers',
       'Interpreters and Translators',
       'Audio and Video Equipment Technicians', 'Broadcast Technicians',
       'Radio Operators', 'Sound Engineering Technicians',
       'Photographers',
       'Camera Operators, Television, Video, and Motion Picture',
       'Film and Video Editors', 'Chiropractors', 'Dentists, General',
       'Oral and Maxillofacial Surgeons', 'Orthodontists',
       'Prosthodontists', 'Dietitians and Nutritionists', 'Optometrists',
       'Pharmacists', 'Anesthesiologists',
       'Family and General Practitioners', 'Internists, General',
       'Obstetricians and Gynecologists', 'Pediatricians, General',
       'Psychiatrists', 'Surgeons', 'Allergists and Immunologists',
       'Dermatologists', 'Hospitalists', 'Neurologists',
       'Nuclear Medicine Physicians', 'Ophthalmologists', 'Pathologists',
       'Physical Medicine and Rehabilitation Physicians',
       'Preventive Medicine Physicians', 'Radiologists',
       'Sports Medicine Physicians', 'Urologists', 'Physician Assistants',
       'Anesthesiologist Assistants', 'Podiatrists',
       'Occupational Therapists',
       'Low Vision Therapists, Orientation and Mobility Specialists, and Vision Rehabilitation Therapists',
       'Physical Therapists', 'Radiation Therapists',
       'Recreational Therapists', 'Art Therapists', 'Music Therapists',
       'Respiratory Therapists', 'Speech-Language Pathologists',
       'Exercise Physiologists', 'Veterinarians', 'Registered Nurses',
       'Acute Care Nurses', 'Advanced Practice Psychiatric Nurses',
       'Critical Care Nurses', 'Clinical Nurse Specialists',
       'Nurse Anesthetists', 'Nurse Midwives', 'Nurse Practitioners',
       'Audiologists', 'Acupuncturists', 'Naturopathic Physicians',
       'Orthoptists', 'Medical and Clinical Laboratory Technologists',
       'Cytogenetic Technologists', 'Cytotechnologists',
       'Histotechnologists and Histologic Technicians',
       'Medical and Clinical Laboratory Technicians', 'Dental Hygienists',
       'Cardiovascular Technologists and Technicians',
       'Diagnostic Medical Sonographers',
       'Nuclear Medicine Technologists', 'Radiologic Technologists',
       'Magnetic Resonance Imaging Technologists',
       'Emergency Medical Technicians and Paramedics',
       'Dietetic Technicians', 'Pharmacy Technicians',
       'Psychiatric Technicians', 'Respiratory Therapy Technicians',
       'Surgical Technologists',
       'Veterinary Technologists and Technicians',
       'Ophthalmic Medical Technicians',
       'Licensed Practical and Licensed Vocational Nurses',
       'Medical Records and Health Information Technicians',
       'Opticians, Dispensing', 'Orthotists and Prosthetists',
       'Hearing Aid Specialists', 'Neurodiagnostic Technologists',
       'Ophthalmic Medical Technologists', 'Radiologic Technicians',
       'Surgical Assistants',
       'Occupational Health and Safety Specialists',
       'Occupational Health and Safety Technicians', 'Athletic Trainers',
       'Genetic Counselors', 'Midwives', 'Home Health Aides',
       'Psychiatric Aides', 'Nursing Assistants',
       'Occupational Therapy Assistants', 'Occupational Therapy Aides',
       'Physical Therapist Assistants', 'Physical Therapist Aides',
       'Massage Therapists', 'Dental Assistants', 'Medical Assistants',
       'Medical Equipment Preparers', 'Medical Transcriptionists',
       'Pharmacy Aides',
       'Veterinary Assistants and Laboratory Animal Caretakers',
       'Phlebotomists', 'Speech-Language Pathology Assistants',
       'Endoscopy Technicians',
       'First-Line Supervisors of Correctional Officers',
       'First-Line Supervisors of Police and Detectives',
       'Municipal Fire Fighting and Prevention Supervisors',
       'Forest Fire Fighting and Prevention Supervisors',
       'Municipal Firefighters', 'Forest Firefighters', 'Fire Inspectors',
       'Fire Investigators',
       'Forest Fire Inspectors and Prevention Specialists', 'Bailiffs',
       'Correctional Officers and Jailers', 'Police Detectives',
       'Police Identification and Records Officers',
       'Criminal Investigators and Special Agents',
       'Immigration and Customs Inspectors', 'Intelligence Analysts',
       'Fish and Game Wardens', 'Parking Enforcement Workers',
       'Police Patrol Officers', 'Sheriffs and Deputy Sheriffs',
       'Transit and Railroad Police', 'Animal Control Workers',
       'Private Detectives and Investigators',
       'Gaming Surveillance Officers and Gaming Investigators',
       'Security Guards', 'Crossing Guards',
       'Lifeguards, Ski Patrol, and Other Recreational Protective Service Workers',
       'Transportation Security Screeners',
       'Retail Loss Prevention Specialists', 'Chefs and Head Cooks',
       'First-Line Supervisors of Food Preparation and Serving Workers',
       'Cooks, Fast Food', 'Cooks, Institution and Cafeteria',
       'Cooks, Private Household', 'Cooks, Restaurant',
       'Cooks, Short Order', 'Food Preparation Workers', 'Bartenders',
       'Combined Food Preparation and Serving Workers, Including Fast Food',
       'Counter Attendants, Cafeteria, Food Concession, and Coffee Shop',
       'Baristas', 'Waiters and Waitresses',
       'Food Servers, Nonrestaurant',
       'Dining Room and Cafeteria Attendants and Bartender Helpers',
       'Dishwashers',
       'Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop',
       'First-Line Supervisors of Housekeeping and Janitorial Workers',

In [7]:
df = pd.DataFrame(Unititle, columns = ['title'])
df

                                         title
0                             Chief Executives
1                Chief Sustainability Officers
2              General and Operations Managers
3          Advertising and Promotions Managers
4                           Marketing Managers
..                                         ...
949    Pump Operators, Except Wellhead Pumpers
950                           Wellhead Pumpers
951  Refuse and Recyclable Material Collectors
952                 Mine Shuttle Car Operators
953          Tank Car, Truck, and Ship Loaders

[954 rows x 1 columns]

In [8]:
true.rename(columns={'Element Name':'Element_Name'}, inplace=True)

true
#changes column name

,Title,Element_Name,Category,Data Value,Date
0,Chief Executives,Public Speaking,NaN,3.39,07/2014
1,Chief Executives,Public Speaking,1.0,6.02,07/2014
2,Chief Executives,Public Speaking,2.0,12.40,07/2014
3,Chief Executives,Public Speaking,3.0,23.36,07/2014
4,Chief Executives,Public Speaking,4.0,52.55,07/2014
...,...,...,...,...,...
321585,"Tank Car, Truck, and Ship Loaders",Work Schedules,3.0,1.28,12/2006
321586,"Tank Car, Truck, and Ship Loaders",Duration of Typical Work Week,NaN,2.76,12/2006
321587,"Tank Car, Truck, and Ship Loaders",Duration of Typical Work Week,1.0,0.00,12/2006
321588,"Tank Car, Truck, and Ship Loaders",Duration of Typical Work Week,2.0,23.54,12/2006
321589,"Tank Car, Truck, and Ship Loaders",Duration of Typical Work Week,3.0,76.46,12/2006

In [10]:
element = true.Element_Name.unique()
element

array(['Public Speaking', 'Telephone', 'Electronic Mail',
       'Letters and Memos', 'Face-to-Face Discussions',
       'Contact With Others', 'Work With Work Group or Team',
       'Deal With External Customers', 'Coordinate or Lead Others',
       "Responsible for Others' Health and Safety",
       'Responsibility for Outcomes and Results',
       'Frequency of Conflict Situations',
       'Deal With Unpleasant or Angry People',
       'Deal With Physically Aggressive People',
       'Indoors, Environmentally Controlled',
       'Indoors, Not Environmentally Controlled',
       'Outdoors, Exposed to Weather', 'Outdoors, Under Cover',
       'In an Open Vehicle or Equipment',
       'In an Enclosed Vehicle or Equipment', 'Physical Proximity',
       'Sounds, Noise Levels Are Distracting or Uncomfortable',
       'Very Hot or Cold Temperatures',
       'Extremely Bright or Inadequate Lighting',
       'Exposed to Contaminants', 'Cramped Work Space, Awkward Positions',
       'Exposed to Whole Body Vibration', 'Exposed to Radiation',
       'Exposed to Disease or Infections', 'Exposed to High Places',
       'Exposed to Hazardous Conditions',
       'Exposed to Hazardous Equipment',
       'Exposed to Minor Burns, Cuts, Bites, or Stings',
       'Spend Time Sitting', 'Spend Time Standing',
       'Spend Time Climbing Ladders, Scaffolds, or Poles',
       'Spend Time Walking and Running',
       'Spend Time Kneeling, Crouching, Stooping, or Crawling',
       'Spend Time Keeping or Regaining Balance',
       'Spend Time Using Your Hands to Handle, Control, or Feel Objects, Tools, or Controls',
       'Spend Time Bending or Twisting the Body',
       'Spend Time Making Repetitive Motions',
       'Wear Common Protective or Safety Equipment such as Safety Shoes, Glasses, Gloves, Hearing Protection, Hard Hats, or Life Jackets',
       'Wear Specialized Protective or Safety Equipment such as Breathing Apparatus, Safety Harness, Full Protection Suits, or Radiation Protection',
       'Consequence of Error',
       'Impact of Decisions on Co-workers or Company Results',
       'Frequency of Decision Making', 'Freedom to Make Decisions',
       'Degree of Automation', 'Importance of Being Exact or Accurate',
       'Importance of Repeating Same Tasks',
       'Structured versus Unstructured Work', 'Level of Competition',
       'Time Pressure', 'Pace Determined by Speed of Equipment',
       'Work Schedules', 'Duration of Typical Work Week'], dtype=object)

In [11]:
element_list = pd.DataFrame(element, columns = ['Element'])
type(element_list)

pandas.core.frame.DataFrame

In [10]:
#for Q in df.index: 
#     print(df['Column_A'][Q],)
#for Q in df.index: 
    # x= (df['Column_A'][Q],)
#print(type(x))

KeyError: 'Column_A'

In [ ]:
for job in df["title"]:
    for element in element_list["Element"]:
    
    #print(str(job)+", "+(str(element)))

In [15]:
#create output data frame 
score_by_title_element = pd.DataFrame(columns = ["title","element","score"])

temp = []

for i, job in enumerate( df["title"]):
    for element in element_list["Element"]:                             # selecting rows based on condit
        result_df = true[(true['Element_Name'] == element ) & 
                (true['Title'] == job)]
        #importance = rslt_df['Data Value']
        #print(result_df)
        #print(result_df.iloc[1].loc["Data Value"])
        try:
            #percentage of days doing the action days out of the year so exponetial system  -- multiple by days... number of week day... by percent
            #other 3 thing
            score = 0 * result_df.iloc[1].loc["Data Value"] + .043809*result_df.iloc[2].loc["Data Value"]+ .12380952*result_df.iloc[3].loc["Data Value"]+ .6*result_df.iloc[4].loc["Data Value"]+ result_df.iloc[5].loc["Data Value"]
            new_row = {"title":job, "element": element, "score": score}
            score_by_title_element.append(new_row, ignore_index=True)
        except IndexError: # catch the error
             pass
            #if IndexError:
          #  score = -1 * result_df.iloc[1].loc["Data Value"] + result_df.iloc[3].loc["Data Value"]
        
        #append to the output a row with of form [job,element,score]
        temp.append([job, element, score])
    if i==2:
        break
        
        
        #LabeledScore = pd.DataFrame(job, element, score, columns = ['title', 'Element Name', 'Score'])
        
       # new_row = {"title":job, "element": element, "score": score}
       # score_by_title_element.append(new_row, ignore_index=True)

   
    
score_by_title_element2014 = pd.DataFrame(temp,columns=['Title','Description','Score'])
type(score_by_title_element2014)

pandas.core.frame.DataFrame

In [16]:
print(score_by_title_element2014)

                               Title                            Description  \
0                   Chief Executives                        Public Speaking
1                   Chief Executives                              Telephone
2                   Chief Executives                        Electronic Mail
3                   Chief Executives                      Letters and Memos
4                   Chief Executives               Face-to-Face Discussions
..                               ...                                    ...
166  General and Operations Managers                   Level of Competition
167  General and Operations Managers                          Time Pressure
168  General and Operations Managers  Pace Determined by Speed of Equipment
169  General and Operations Managers                         Work Schedules
170  General and Operations Managers          Duration of Typical Work Week

          Score
0     40.635422
1    100.000000
2    100.000000
3     71.807619
4     99.208000
..          ...
166   47.009578
167   66.771524
168   11.237366
169   11.237366
170   11.237366

[171 rows x 3 columns]

In [ ]:
# selecting rows based on condition 
#rslt_df = dataframe[(dataframe['Age'] == 21) & 
#          dataframe['Stream'].isin(options)] 
rslt_df = dataframe[(dataframe['Age'] == 21) & 
          dataframe['Stream'].isin(options)]

In [33]:
type(score_by_title_element)

pandas.core.frame.DataFrame

In [92]:
score_by_title_element.to_excel(r'LaborScores2014.xlsx', index = False)

In [104]:
#all of textfile except main loop
#5
dftxt.rename(columns={'O*NET-SOC Code':'ONETSOC_Code'}, inplace=True)

dftxt
Unititle1 = dftxt.ONETSOC_Code.unique()
Unititle1

array(['11-1011.00', '11-1011.03', '11-1021.00', '11-2011.00',
       '11-2021.00', '11-2022.00', '11-2031.00', '11-3011.00',
       '11-3021.00', '11-3031.01', '11-3031.02', '11-3051.00',
       '11-3051.01', '11-3051.02', '11-3051.03', '11-3051.04',
       '11-3051.06', '11-3061.00', '11-3071.01', '11-3071.02',
       '11-3071.03', '11-3111.00', '11-3121.00', '11-3131.00',
       '11-9013.01', '11-9013.02', '11-9013.03', '11-9021.00',
       '11-9031.00', '11-9032.00', '11-9033.00', '11-9039.01',
       '11-9039.02', '11-9041.00', '11-9041.01', '11-9051.00',
       '11-9061.00', '11-9071.00', '11-9081.00', '11-9111.00',
       '11-9121.00', '11-9121.01', '11-9121.02', '11-9131.00',
       '11-9141.00', '11-9151.00', '11-9161.00', '11-9199.01',
       '11-9199.02', '11-9199.03', '11-9199.04', '11-9199.07',
       '11-9199.08', '11-9199.09', '11-9199.10', '11-9199.11',
       '13-1011.00', '13-1021.00', '13-1022.00', '13-1023.00',
       '13-1031.01', '13-1031.02', '13-1032.00', '13-1041.01',
       '13-1041.02', '13-1041.03', '13-1041.04', '13-1041.06',
       '13-1041.07', '13-1051.00', '13-1071.00', '13-1074.00',
       '13-1075.00', '13-1081.00', '13-1081.01', '13-1081.02',
       '13-1111.00', '13-1121.00', '13-1131.00', '13-1141.00',
       '13-1151.00', '13-1161.00', '13-1199.01', '13-1199.02',
       '13-1199.03', '13-1199.04', '13-1199.05', '13-1199.06',
       '13-2011.01', '13-2011.02', '13-2021.01', '13-2021.02',
       '13-2031.00', '13-2041.00', '13-2051.00', '13-2052.00',
       '13-2053.00', '13-2061.00', '13-2071.00', '13-2071.01',
       '13-2072.00', '13-2081.00', '13-2082.00', '13-2099.01',
       '13-2099.02', '13-2099.04', '15-1111.00', '15-1121.00',
       '15-1121.01', '15-1122.00', '15-1131.00', '15-1132.00',
       '15-1133.00', '15-1134.00', '15-1141.00', '15-1142.00',
       '15-1143.00', '15-1143.01', '15-1151.00', '15-1152.00',
       '15-1199.01', '15-1199.02', '15-1199.03', '15-1199.04',
       '15-1199.05', '15-1199.06', '15-1199.07', '15-1199.08',
       '15-1199.09', '15-1199.10', '15-1199.11', '15-1199.12',
       '15-2011.00', '15-2021.00', '15-2031.00', '15-2041.00',
       '15-2041.01', '15-2041.02', '15-2091.00', '17-1011.00',
       '17-1012.00', '17-1021.00', '17-1022.00', '17-1022.01',
       '17-2011.00', '17-2021.00', '17-2031.00', '17-2041.00',
       '17-2051.00', '17-2051.01', '17-2061.00', '17-2071.00',
       '17-2072.00', '17-2072.01', '17-2081.00', '17-2081.01',
       '17-2111.01', '17-2111.02', '17-2111.03', '17-2112.00',
       '17-2112.01', '17-2121.01', '17-2121.02', '17-2131.00',
       '17-2141.00', '17-2141.01', '17-2141.02', '17-2151.00',
       '17-2161.00', '17-2171.00', '17-2199.01', '17-2199.02',
       '17-2199.03', '17-2199.04', '17-2199.05', '17-2199.06',
       '17-2199.07', '17-2199.08', '17-2199.09', '17-2199.10',
       '17-2199.11', '17-3011.01', '17-3011.02', '17-3012.01',
       '17-3012.02', '17-3013.00', '17-3021.00', '17-3022.00',
       '17-3023.01', '17-3023.03', '17-3024.00', '17-3024.01',
       '17-3025.00', '17-3026.00', '17-3027.00', '17-3027.01',
       '17-3029.01', '17-3029.02', '17-3029.03', '17-3029.04',
       '17-3029.05', '17-3029.06', '17-3029.07', '17-3029.08',
       '17-3029.09', '17-3029.11', '17-3029.12', '17-3031.01',
       '17-3031.02', '19-1011.00', '19-1012.00', '19-1013.00',
       '19-1020.01', '19-1021.00', '19-1022.00', '19-1023.00',
       '19-1029.01', '19-1029.02', '19-1029.03', '19-1031.01',
       '19-1031.02', '19-1031.03', '19-1032.00', '19-1041.00',
       '19-1042.00', '19-2011.00', '19-2012.00', '19-2021.00',
       '19-2031.00', '19-2032.00', '19-2041.00', '19-2041.01',
       '19-2041.02', '19-2041.03', '19-2042.00', '19-2043.00',
       '19-2099.01', '19-3011.00', '19-3011.01', '19-3022.00',
       '19-3031.01', '19-3031.02', '19-3031.03', '19-3032.00',
       '19-3039.01', '19-3041.00', '19-3051.00', '19-3091.01',
       '19-3091.02', '19-3092.00', '19-3093.00', '19-3094.00',
       '19-3099.01', '19-4011.01', '19-4011.02', '19-4021.00',
       '19-4031.00', '19-4041.01', '19-4041.02', '19-4051.01',
       '19-4051.02', '19-4061.00', '19-4061.01', '19-4091.00',
       '19-4092.00', '19-4093.00', '19-4099.01', '19-4099.02',
       '19-4099.03', '21-1011.00', '21-1012.00', '21-1013.00',
       '21-1014.00', '21-1015.00', '21-1021.00', '21-1022.00',
       '21-1023.00', '21-1091.00', '21-1092.00', '21-1093.00',
       '21-1094.00', '21-2011.00', '21-2021.00', '23-1011.00',
       '23-1012.00', '23-1021.00', '23-1022.00', '23-1023.00',
       '23-2011.00', '23-2091.00', '23-2093.00', '25-1011.00',
       '25-1021.00', '25-1022.00', '25-1031.00', '25-1032.00',
       '25-1041.00', '25-1042.00', '25-1043.00', '25-1051.00',
       '25-1052.00', '25-1053.00', '25-1054.00', '25-1061.00',
       '25-1062.00', '25-1063.00', '25-1064.00', '25-1065.00',
       '25-1066.00', '25-1067.00', '25-1071.00', '25-1072.00',
       '25-1081.00', '25-1082.00', '25-1111.00', '25-1112.00',
       '25-1113.00', '25-1121.00', '25-1122.00', '25-1123.00',
       '25-1124.00', '25-1125.00', '25-1126.00', '25-1191.00',
       '25-1192.00', '25-1193.00', '25-1194.00', '25-2011.00',
       '25-2012.00', '25-2021.00', '25-2022.00', '25-2023.00',
       '25-2031.00', '25-2032.00', '25-2051.00', '25-2052.00',
       '25-2053.00', '25-2054.00', '25-2059.01', '25-3011.00',
       '25-3021.00', '25-3099.02', '25-4011.00', '25-4012.00',
       '25-4013.00', '25-4021.00', '25-4031.00', '25-9011.00',
       '25-9021.00', '25-9031.00', '25-9031.01', '25-9041.00',
       '27-1011.00', '27-1012.00', '27-1013.00', '27-1014.00',
       '27-1021.00', '27-1022.00', '27-1023.00', '27-1024.00',
       '27-1025.00', '27-1026.00', '27-1027.00', '27-2011.00',
       '27-2012.01', '27-2012.02', '27-2012.03', '27-2012.04',
       '27-2012.05', '27-2021.00', '27-2022.00', '27-2023.00',
       '27-2031.00', '27-2032.00', '27-2041.01', '27-2041.04',
       '27-2042.01', '27-2042.02', '27-3011.00', '27-3012.00',
       '27-3021.00', '27-3022.00', '27-3031.00', '27-3041.00',
       '27-3042.00', '27-3043.04', '27-3043.05', '27-3091.00',
       '27-4011.00', '27-4012.00', '27-4013.00', '27-4014.00',
       '27-4021.00', '27-4031.00', '27-4032.00', '29-1011.00',
       '29-1021.00', '29-1022.00', '29-1023.00', '29-1024.00',
       '29-1031.00', '29-1041.00', '29-1051.00', '29-1061.00',
       '29-1062.00', '29-1063.00', '29-1064.00', '29-1065.00',
       '29-1066.00', '29-1067.00', '29-1069.01', '29-1069.02',
       '29-1069.03', '29-1069.04', '29-1069.05', '29-1069.06',
       '29-1069.07', '29-1069.08', '29-1069.09', '29-1069.10',
       '29-1069.11', '29-1069.12', '29-1071.00', '29-1071.01',
       '29-1081.00', '29-1122.00', '29-1122.01', '29-1123.00',
       '29-1124.00', '29-1125.00', '29-1125.01', '29-1125.02',
       '29-1126.00', '29-1127.00', '29-1128.00', '29-1131.00',
       '29-1141.00', '29-1141.01', '29-1141.02', '29-1141.03',
       '29-1141.04', '29-1151.00', '29-1161.00', '29-1171.00',
       '29-1181.00', '29-1199.01', '29-1199.04', '29-1199.05',
       '29-2011.00', '29-2011.01', '29-2011.02', '29-2011.03',
       '29-2012.00', '29-2021.00', '29-2031.00', '29-2032.00',
       '29-2033.00', '29-2034.00', '29-2035.00', '29-2041.00',
       '29-2051.00', '29-2052.00', '29-2053.00', '29-2054.00',
       '29-2055.00', '29-2056.00', '29-2057.00', '29-2061.00',
       '29-2071.00', '29-2081.00', '29-2091.00', '29-2092.00',
       '29-2099.01', '29-2099.05', '29-2099.06', '29-2099.07',
       '29-9011.00', '29-9012.00', '29-9091.00', '29-9092.00',
       '29-9099.01', '31-1011.00', '31-1013.00', '31-1014.00',
       '31-1015.00', '31-2011.00', '31-2012.00', '31-2021.00',
       '31-2022.00', '31-9011.00', '31-9091.00', '31-9092.00',
       '31-9093.00', '31-9094.00', '31-9095.00', '31-9096.00',
       '31-9097.00', '31-9099.01', '31-9099.02', '33-1011.00',
       '33-1012.00', '33-1021.01', '33-1021.02', '33-2011.01',
       '33-2011.02', '33-2021.01', '33-2021.02', '33-2022.00',
       '33-3011.00', '33-3012.00', '33-3021.01', '33-3021.02',
       '33-3021.03', '33-3021.05', '33-3021.06', '33-3031.00',
       '33-3041.00', '33-3051.01', '33-3051.03', '33-3052.00',
       '33-9011.00', '33-9021.00', '33-9031.00', '33-9032.00',
       '33-9091.00', '33-9092.00', '33-9093.00', '33-9099.02',
       '35-1011.00', '35-1012.00', '35-2011.00', '35-2012.00',
       '35-2013.00', '35-2014.00', '35-2015.00', '35-2021.00',
       '35-3011.00', '35-3021.00', '35-3022.00', '35-3022.01',
       '35-3031.00', '35-3041.00', '35-9011.00', '35-9021.00',
       '35-9031.00', '37-1011.00', '37-1012.00', '37-2011.00',
       '37-2012.00', '37-2021.00', '37-3011.00', '37-3012.00',
       '37-3013.00', '39-1011.00', '39-1012.00', '39-1021.00',
       '39-1021.01', '39-2011.00', '39-2021.00', '39-3011.00',
       '39-3012.00', '39-3021.00', '39-3031.00', '39-3091.00',
       '39-3092.00', '39-3093.00', '39-4011.00', '39-4021.00',
       '39-4031.00', '39-5011.00', '39-5012.00', '39-5091.00',
       '39-5092.00', '39-5093.00', '39-5094.00', '39-6011.00',
       '39-6012.00', '39-7011.00', '39-7012.00', '39-9011.00',
       '39-9011.01', '39-9021.00', '39-9031.00', '39-9032.00',
       '39-9041.00', '41-1011.00', '41-1012.00', '41-2011.00',
       '41-2012.00', '41-2021.00', '41-2022.00', '41-2031.00',
       '41-3011.00', '41-3021.00', '41-3031.01', '41-3031.02',
       '41-3031.03', '41-3041.00', '41-3099.01', '41-4011.00',
       '41-4011.07', '41-4012.00', '41-9011.00', '41-9012.00',
       '41-9021.00', '41-9022.00', '41-9031.00', '41-9041.00',
       '41-9091.00', '43-1011.00', '43-2011.00', '43-2021.00',
       '43-3011.00', '43-3021.01', '43-3021.02', '43-3031.00',
       '43-3041.00', '43-3051.00', '43-3061.00', '43-3071.00',
       '43-4011.00', '43-4021.00', '43-4031.01', '43-4031.02',
       '43-4031.03', '43-4041.01', '43-4041.02', '43-4051.00',
       '43-4051.03', '43-4061.00', '43-4071.00', '43-4081.00',
       '43-4111.00', '43-4121.00', '43-4131.00', '43-4141.00',
       '43-4151.00', '43-4161.00', '43-4171.00', '43-4181.00',
       '43-5011.00', '43-5011.01', '43-5021.00', '43-5031.00',
       '43-5032.00', '43-5041.00', '43-5051.00', '43-5052.00',
       '43-5053.00', '43-5061.00', '43-5071.00', '43-5081.01',
       '43-5081.02', '43-5081.03', '43-5081.04', '43-5111.00',
       '43-6011.00', '43-6012.00', '43-6013.00', '43-6014.00',
       '43-9011.00', '43-9021.00', '43-9022.00', '43-9031.00',
       '43-9041.01', '43-9041.02', '43-9051.00', '43-9061.00',
       '43-9071.00', '43-9081.00', '43-9111.00', '43-9111.01',
       '45-1011.05', '45-1011.06', '45-1011.07', '45-1011.08',
       '45-2011.00', '45-2021.00', '45-2041.00', '45-2091.00',
       '45-2092.01', '45-2092.02', '45-2093.00', '45-3011.00',
       '45-3021.00', '45-4011.00', '45-4021.00', '45-4022.00',
       '45-4023.00', '47-1011.00', '47-1011.03', '47-2011.00',
       '47-2021.00', '47-2022.00', '47-2031.01', '47-2031.02',
       '47-2041.00', '47-2042.00', '47-2043.00', '47-2044.00',
       '47-2051.00', '47-2053.00', '47-2061.00', '47-2071.00',
       '47-2072.00', '47-2073.00', '47-2081.00', '47-2082.00',
       '47-2111.00', '47-2121.00', '47-2131.00', '47-2132.00',
       '47-2141.00', '47-2142.00', '47-2151.00', '47-2152.01',
       '47-2152.02', '47-2161.00', '47-2171.00', '47-2181.00',
       '47-2211.00', '47-2221.00', '47-2231.00', '47-3011.00',
       '47-3012.00', '47-3013.00', '47-3014.00', '47-3015.00',
       '47-3016.00', '47-4011.00', '47-4021.00', '47-4031.00',
       '47-4041.00', '47-4051.00', '47-4061.00', '47-4071.00',
       '47-4091.00', '47-4099.02', '47-4099.03', '47-5011.00',
       '47-5012.00', '47-5013.00', '47-5021.00', '47-5031.00',
       '47-5041.00', '47-5042.00', '47-5051.00', '47-5061.00',
       '47-5071.00', '47-5081.00', '49-1011.00', '49-2011.00',
       '49-2021.00', '49-2021.01', '49-2022.00', '49-2091.00',
       '49-2092.00', '49-2093.00', '49-2094.00', '49-2095.00',
       '49-2096.00', '49-2097.00', '49-2098.00', '49-3011.00',
       '49-3021.00', '49-3022.00', '49-3023.01', '49-3023.02',
       '49-3031.00', '49-3041.00', '49-3042.00', '49-3043.00',
       '49-3051.00', '49-3052.00', '49-3053.00', '49-3091.00',
       '49-3092.00', '49-3093.00', '49-9011.00', '49-9012.00',
       '49-9021.01', '49-9021.02', '49-9031.00', '49-9041.00',
       '49-9043.00', '49-9044.00', '49-9045.00', '49-9051.00',
       '49-9052.00', '49-9061.00', '49-9062.00', '49-9063.00',
       '49-9064.00', '49-9071.00', '49-9081.00', '49-9091.00',
       '49-9092.00', '49-9093.00', '49-9094.00', '49-9095.00',
       '49-9096.00', '49-9097.00', '49-9098.00', '49-9099.01',
       '51-1011.00', '51-2011.00', '51-2021.00', '51-2022.00',
       '51-2023.00', '51-2031.00', '51-2041.00', '51-2091.00',
       '51-2092.00', '51-2093.00', '51-3011.00', '51-3021.00',
       '51-3022.00', '51-3023.00', '51-3091.00', '51-3092.00',
       '51-3093.00', '51-4011.00', '51-4012.00', '51-4021.00',
       '51-4022.00', '51-4023.00', '51-4031.00', '51-4032.00',
       '51-4033.00', '51-4034.00', '51-4035.00', '51-4041.00',
       '51-4051.00', '51-4052.00', '51-4061.00', '51-4062.00',
       '51-4071.00', '51-4072.00', '51-4081.00', '51-4111.00',
       '51-4121.06', '51-4121.07', '51-4122.00', '51-4191.00',
       '51-4192.00', '51-4193.00', '51-4194.00', '51-5111.00',
       '51-5112.00', '51-5113.00', '51-6011.00', '51-6021.00',
       '51-6031.00', '51-6041.00', '51-6042.00', '51-6051.00',
       '51-6052.00', '51-6061.00', '51-6062.00', '51-6063.00',
       '51-6064.00', '51-6091.00', '51-6092.00', '51-6093.00',
       '51-7011.00', '51-7021.00', '51-7031.00', '51-7032.00',
       '51-7041.00', '51-7042.00', '51-8011.00', '51-8012.00',
       '51-8013.00', '51-8021.00', '51-8031.00', '51-8091.00',
       '51-8092.00', '51-8093.00', '51-8099.01', '51-8099.03',
       '51-8099.04', '51-9011.00', '51-9012.00', '51-9021.00',
       '51-9022.00', '51-9023.00', '51-9031.00', '51-9032.00',
       '51-9041.00', '51-9051.00', '51-9061.00', '51-9071.01',
       '51-9071.06', '51-9071.07', '51-9081.00', '51-9082.00',
       '51-9083.00', '51-9111.00', '51-9121.00', '51-9122.00',
       '51-9123.00', '51-9141.00', '51-9151.00', '51-9191.00',
       '51-9192.00', '51-9193.00', '51-9194.00', '51-9195.03',
       '51-9195.04', '51-9195.05', '51-9195.07', '51-9196.00',
       '51-9197.00', '51-9198.00', '51-9199.01', '53-1011.00',
       '53-1021.00', '53-1021.01', '53-1031.00', '53-2011.00',
       '53-2012.00', '53-2021.00', '53-2022.00', '53-2031.00',
       '53-3011.00', '53-3021.00', '53-3022.00', '53-3031.00',
       '53-3032.00', '53-3033.00', '53-3041.00', '53-4011.00',
       '53-4012.00', '53-4013.00', '53-4021.00', '53-4031.00',
       '53-4041.00', '53-5011.00', '53-5021.01', '53-5021.02',
       '53-5021.03', '53-5022.00', '53-5031.00', '53-6011.00',
       '53-6021.00', '53-6031.00', '53-6041.00', '53-6051.01',
       '53-6051.07', '53-6051.08', '53-6061.00', '53-7011.00',
       '53-7021.00', '53-7031.00', '53-7032.00', '53-7033.00',
       '53-7041.00', '53-7051.00', '53-7061.00', '53-7062.00',
       '53-7063.00', '53-7064.00', '53-7071.00', '53-7072.00',
       '53-7073.00', '53-7081.00', '53-7111.00', '53-7121.00'],
      dtype=object)

In [105]:
#6
df1 = pd.DataFrame(Unititle1, columns = ['title1'])
df1

         title1
0    11-1011.00
1    11-1011.03
2    11-1021.00
3    11-2011.00
4    11-2021.00
..          ...
963  53-7072.00
964  53-7073.00
965  53-7081.00
966  53-7111.00
967  53-7121.00

[968 rows x 1 columns]

In [106]:
#7
dftxt.rename(columns={'Element Name':'Element_Name1'}, inplace=True)

dftxt

,ONETSOC_Code,Element_Name,Category,Data Value,Date
0,11-1011.00,Public Speaking,NaN,3.39,07/2014
1,11-1011.00,Public Speaking,1.0,6.02,07/2014
2,11-1011.00,Public Speaking,2.0,12.40,07/2014
3,11-1011.00,Public Speaking,3.0,23.36,07/2014
4,11-1011.00,Public Speaking,4.0,52.55,07/2014
...,...,...,...,...,...
326879,53-7121.00,Work Schedules,3.0,0.89,08/2019
326880,53-7121.00,Duration of Typical Work Week,NaN,2.82,08/2019
326881,53-7121.00,Duration of Typical Work Week,1.0,0.00,08/2019
326882,53-7121.00,Duration of Typical Work Week,2.0,17.56,08/2019
326883,53-7121.00,Duration of Typical Work Week,3.0,82.44,08/2019

In [107]:
element1 = true.Element_Name1.unique()
element1

AttributeError: 'DataFrame' object has no attribute 'Element_Name1'

In [101]:
element_list1 = pd.DataFrame(element1, columns = ['Element1'])
type(element_list1)

pandas.core.frame.DataFrame

In [102]:
#create output data frame 
#score_by_title_element = pd.DataFrame(columns = ["title","element","score"])

temp = []

for i, job in enumerate( df["title1"]):
    for element1 in element_list1["Element1"]:                             # selecting rows based on condit
        result_df = dftxt[(dftxt['Element_Name1'] == element ) & 
                (dftxt['ONETSOC_Code'] == job)]
        #importance = rslt_df['Data Value']
        #print(result_df)
        #print(result_df.iloc[1].loc["Data Value"])
        try:
            #percentage of days doing the action days out of the year so exponetial system  -- multiple by days... number of week day... by percent
            #other 3 thing
            score = 0 * result_df.iloc[1].loc["Data Value"] + .043809*result_df.iloc[2].loc["Data Value"]+ .12380952*result_df.iloc[3].loc["Data Value"]+ .6*result_df.iloc[4].loc["Data Value"]+ result_df.iloc[5].loc["Data Value"]
            new_row = {"title":job, "element": element, "score": score}
            score_by_title_element.append(new_row, ignore_index=True)
        except IndexError: # catch the error
             pass
            #if IndexError:
          #  score = -1 * result_df.iloc[1].loc["Data Value"] + result_df.iloc[3].loc["Data Value"]
        
        #append to the output a row with of form [job,element,score]
        temp.append([job, element, score])
    if i==2:
        break
        
        
        #LabeledScore = pd.DataFrame(job, element, score, columns = ['title', 'Element Name', 'Score'])
        
       # new_row = {"title":job, "element": element, "score": score}
       # score_by_title_element.append(new_row, ignore_index=True)

   
    
score_by_title_element2006 = pd.DataFrame(temp,columns=['Title','Description','Score'])
type(score_by_title_element2006)

pandas.core.frame.DataFrame

In [103]:

print(score_by_title_element2006)

                               Title                            Description  \
0                   Chief Executives                        Public Speaking
1                   Chief Executives                              Telephone
2                   Chief Executives                        Electronic Mail
3                   Chief Executives                      Letters and Memos
4                   Chief Executives               Face-to-Face Discussions
..                               ...                                    ...
166  General and Operations Managers                   Level of Competition
167  General and Operations Managers                          Time Pressure
168  General and Operations Managers  Pace Determined by Speed of Equipment
169  General and Operations Managers                         Work Schedules
170  General and Operations Managers          Duration of Typical Work Week

         Score
0    62.684551
1    62.684551
2    62.684551
3    62.684551
4    62.684551
..         ...
166  62.684551
167  62.684551
168  62.684551
169  62.684551
170  62.684551

[171 rows x 3 columns]

In [78]:
score_by_title_element2006.to_excel(r'LaborScores2006.xlsx', index = False)